# Generated by Django 3.0.4 on 2020-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200321_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='probability',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='token_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
