# Generated by Django 3.0.4 on 2020-03-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200321_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='session',
            field=models.CharField(max_length=255),
        ),
    ]
