# Generated by Django 3.0.4 on 2020-03-22 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20200321_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255)),
                ('tokens_playing_for', models.IntegerField()),
                ('tokens_won', models.IntegerField()),
                ('tokens_remaining', models.IntegerField()),
                ('won_on_number', models.IntegerField(blank=True, null=True)),
                ('is_jackpot', models.BooleanField(default=False)),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
