# Generated by Django 3.0.4 on 2020-03-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200322_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='probability',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
