# Generated by Django 3.0.4 on 2020-03-17 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTokenTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_amount', models.IntegerField()),
                ('is_token_purchased', models.IntegerField()),
                ('is_token_granted', models.IntegerField()),
                ('transaction_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'available_token_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('round_id', models.AutoField(primary_key=True, serialize=False)),
                ('tokens_playing_for', models.IntegerField()),
                ('tokens_won', models.IntegerField()),
                ('tokens_remaining', models.IntegerField()),
                ('won_on_number', models.IntegerField(blank=True, null=True)),
                ('is_jackpot', models.IntegerField()),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_round',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_log_in_time', models.DateTimeField(blank=True, null=True)),
                ('session_log_out_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(max_length=25)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WinningNoHistory',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('probability', models.IntegerField()),
                ('is_active', models.IntegerField(default=1)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(9999, 12, 31))),
            ],
            options={
                'db_table': 'winning_no_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AggAvailableToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.User')),
                ('available_token', models.IntegerField()),
            ],
            options={
                'db_table': 'agg_available_token',
                'managed': False,
            },
        ),
    ]
